### ISSUE TITLE
modules is not working 

### ISSUE THREAD

**Issue by meenal9** [medusajs/examples#16]
@medusajs/framework/utils -- its throwing error

**Comment by shahednasser** [comment]
@meenal9 any issues you've had should be fixed now after the latest push. If not, please re-open this issue with more details on what errors you're facing.

**Comment by meenal9** [comment]
Hi @shahednasser,

Thank you for your prompt resolution to my previous issue!

I’m currently working with the /vendors/products endpoint. While the response was initially limited, I’ve successfully added fields for variants.*, and everything is working as expected. However, I’ve encountered the following issues:

When attempting to include variant.price.* fields (as per the documentation: https://docs.medusajs.com/resources/commerce-modules/product/guides/price), I’m encountering errors. Although the calculated price appears to be working fine, the fields for variant.price.* are not being resolved and return errors instead.

The option.values field consistently comes up blank, even when it should have data.

It seems like this could potentially be a Medusa issue. Any guidance or suggestions on resolving these problems would be greatly appreciated!

Thank you in advance!
