### ISSUE TITLE
marketplace example TS issue; completeCartWorkflow does not return OrderDto?

### ISSUE THREAD

**Issue by andriykrasnychuk** [medusajs/examples#17]
https://github.com/medusajs/examples/blame/ac5fa3ffa95a6621218b0c466aa041b25033b8e3/marketplace/src/workflows/marketplace/create-vendor-orders/index.ts#L43

> Type '{ id: string | WorkflowData<string>; } & { id: string; } & WorkflowDataProperties<{ id: string; }> & { config(config: { name?: string; } & Omit<TransactionStepsDefinition, "next" | ... 1 more ... | "action">): WorkflowData<...>; } & StepFunctionReturnConfig<...>' is not assignable to type '(OrderDTO | WorkflowData<OrderDTO>) & OrderDTO'.
  Type '{ id: string | WorkflowData<string>; } & { id: string; } & WorkflowDataProperties<{ id: string; }> & { config(config: { name?: string; } & Omit<TransactionStepsDefinition, "next" | ... 1 more ... | "action">): WorkflowData<...>; } & StepFunctionReturnConfig<...>' is not assignable to type '{ id: string | WorkflowData<string>; version: number | WorkflowData<number>; order_change?: OrderChangeDTO | WorkflowData<OrderChangeDTO>; ... 60 more ...; raw_original_shipping_tax_total: BigNumberRawValue | WorkflowData<...>; } & OrderDTO & WorkflowDataProperties<...> & { ...; }'.
    Type '{ id: string | WorkflowData<string>; } & { id: string; } & WorkflowDataProperties<{ id: string; }> & { config(config: { name?: string; } & Omit<TransactionStepsDefinition, "next" | ... 1 more ... | "action">): WorkflowData<...>; } & StepFunctionReturnConfig<...>' is missing the following properties from type '{ id: string | WorkflowData<string>; version: number | WorkflowData<number>; order_change?: OrderChangeDTO | WorkflowData<OrderChangeDTO>; ... 60 more ...; raw_original_shipping_tax_total: BigNumberRawValue | WorkflowData<...>; }': version, status, currency_code, created_at, and 46 more.ts(2322)
create-vendor-orders.ts(25, 3): The expected type comes from property 'parentOrder' which is declared here on type 'StepInput | WorkflowData<StepInput>'

**Comment by shahednasser** [comment]
Nice catch! Just pushed a fix. Will also fix in the documentation.
