### ISSUE TITLE
Subscription example does not update expiration_date?

### ISSUE THREAD

**Issue by samyung0** [medusajs/examples#20]
In `recordNewSubscriptionOrder` which is called from `updateSubscriptionStep`, it only updates the `last_order_date` and `next_order_date` without updating the `expiration_date`. Actually, I don't think the`expiration_date` is ever updated? So when `expireSubscriptionOrdersJob` is run, or when a subscription is updated (renewed) for the second time (`getNextOrderDate` will return null because `nextOrderDate` is after `expirationMomentDate`), the subscriptions `next_order_date` becomes null. Which leads me to the second question: if  `getNextOrderDate` returns null for `updateSubscription` because of stale `expiration_date` or any other reasons, it doesn't seem like there is a mechanism to update the status of the subscription to expired?
Apologies if I am not fully understanding the mechanism of the subscription system.

**Comment by shahednasser** [comment]
Hello, regarding `recordNewSubscriptionOrder`, not really sure why the expiration date would be updated. This method is only to create a new order for an active subscription.

The only time the expiration date should be updated is when the subscription is renewed, which isn't covered by this example. There are different features you can add to the examples, we just cover the basics or general approach for implementing them.

Will close this issue for now. Feel free to ask questions if anything is unclear!

**Comment by samyung0** [comment]
I see, but then in step 10 of creating a scheduled job to create a new subscription order, the purpose is not to renew an existing subscription, but rather to make a new one and attach it to the same customer?

The scheduled job calls `createSubscriptionOrderWorkflow` which makes a whole new subscription rather than renewing it.
