### ISSUE TITLE
Marketplace module not showing in admin

### ISSUE THREAD

**Issue by Tekmindlabs** [medusajs/examples#23]
I have install medusa project frontend and backend, the followed instructions as per marketplace example and migrated db but i am not able to see marketplace module in admin

**Comment by shahednasser** [comment]
Hello, thank you for reporting this issue. what exactly are you expecting to see? The marketplace example doesn't have admin customizations.

**Comment by shahednasser** [comment]
Closing this issue due to lack of response. Feel free to re-open with more information.
