### ISSUE TITLE
Missing src/jobs folder in documentation for digital product example

### ISSUE THREAD

**Issue by Deystr0** [medusajs/examples#25]
While following the [Digital Product Example guide](https://github.com/medusajs/examples/tree/main/digital-product#copy-into-existing-medusa-application), I noticed that the instructions mention copying a src/jobs directory. However, the repository does not contain a folder named src/jobs, which could lead to confusion.

### Relevant Section of the Documentation
Medusa v2 Example: Digital Product
Copy into Existing Medusa Application
If you have an existing Medusa application, copy the content of the following directories:

1. src/modules/digital-product
2. src/links
3. src/workflows
4. src/api
5. src/admin
6. src/jobs

### Steps to Reproduce
Visit the [Digital Product Example](https://github.com/medusajs/examples/tree/main/digital-product#copy-into-existing-medusa-application).
Follow the instructions under "Copy into Existing Medusa Application".
Notice that the src/jobs directory is missing from the repository or renamed.

### Expected Behavior
The guide should provide clear instructions, the missing/renamed src/jobs folder should be in the src folder. 

### Suggested Fix
Update the documentation to reflect the actual folder structure.
Clarify whether src/jobs is necessary for implementing the digital product functionality or the new name (that I think is src/subscribers somehow).

**Comment by shahednasser** [comment]
Nice catch! I've updated the README to mention `src/subscribers` instead of `src/jobs`.
